# Generated by Django 4.0.6 on 2022-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PWtest',
            fields=[
                ('pw', models.IntegerField(max_length=8)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
