# Generated by Django 3.2.9 on 2022-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackersapp', '0002_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
